### ISSUE TITLE
Support for Emissions

### ISSUE THREAD

**Issue by chicken-suop** [SnutiHQ/Toon-Shader#2]
<img width="1680" alt="Screen Shot 2020-06-27 at 23 47 19" src="https://user-images.githubusercontent.com/24547185/85923677-7de0b780-b88d-11ea-9027-22ddd9562a74.png">

I'm trying to add lights using emissions, but they aren't affecting the toon shader. Please help

**Comment by chicken-suop** [comment]
<img width="1680" alt="Screen Shot 2020-06-27 at 23 49 36" src="https://user-images.githubusercontent.com/24547185/85923723-d0ba6f00-b88d-11ea-9bbb-a34281bcea89.png">

Setting all elements to Static, gives me this effect. So, the lighting is affecting the Suzzan, but the toon shader isn't being used

**Comment by ecker00** [comment]
Supporting emissive surfaces could technically work, but think this would fall quite far outside scope of a Toon Shader, as it's trying to achieve simplistic shading/lighting look rather than something realistic.

The current setup of the Toon Shader supports directional, point and spot lights. Technically speaking you can make it support anything, as the helper script is just finding the position of all light sources in the scene and assigning colour values from various directions.
